# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09b9b9c28da3823ef6f7d3063a28c0208b10716612c726194d1ed52115e9ba649d995d2332991e24fddf251fec60a413239140633aa030358bd96b6cc13d8e60

test:
  secret_key_base: cbc58964a4b3b3ecfcf6bd7f0538028e7c360fc3fc906e56ae3a26e701e3472eb7680ad3f7739490801eac81eef03bb940835c3d85fa7023677ebdf09e0807be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
